### PR TITLE
Fixes Issue #42 (build script fails)

### PR DESCRIPTION
**Pull request by superherointj**
https://github.com/anmonteiro/aws-lambda-ocaml-runtime/issues/42

### CODE REVIEW

**Comment by anmonteiro** [comment]
Thanks for this -- would you mind adding it to every Dockerfile in the examples folder?

**Comment by superherointj** [comment]
Sure. I'll test all examples. And send patch for each.

**Comment by anmonteiro** [comment]
I really appreciate that -- you may have to bump the esy versions in the Dockerfile to `0.5.8` or `@latest`

**Comment by superherointj** [comment]
Can I set every example dependency to use @latest (docker images, packages, ocaml, etc)? I prefer that behavior because softwares gets outdated quickly. And if it breaks we can always fix it.

**Comment by anmonteiro** [comment]
Yeah I think that's fine

**Comment by superherointj** [comment]
I tried to use git commit but I did not have permission. Then I tried to paste the patch here but GitHub did not accept. So I zipped it. I hope you'll be able to apply it. Sorry for the inconvenience.

[patch-coreutils.zip](https://github.com/anmonteiro/aws-lambda-ocaml-runtime/files/3714953/patch-coreutils.zip)

**Comment by superherointj** [comment]
https://github.com/superherointj/aws-lambda-ocaml-runtime/commit/1d1cfc69a66fb6029084c2af8d982492186b6aa2

**Comment by anmonteiro** [comment]
can you open a new PR from that commit?

**Comment by superherointj** [comment]
Done.

**Pull request closed without merging**
